---
kind: pipeline
name: app

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: ghcr.io
      username: simoneromano96
      password: 
        from_secret: token
      repo: ghcr.io/simoneromano96/graphql-todo/frontend
      context: .
      dockerfile: ./.docker/app.dockerfile
      auto_tag: true
      target: production
      config:
        from_secret: docker_auth_config

---
kind: pipeline
type: ssh
name: deploy

server:
  host:
    from_secret: host
  user:
    from_secret: user
  ssh_key:
    from_secret: ssh_key

steps:
  - name: deploy-docker-app
    commands:
      - cd ~/docker/streams/graphql-todo
      - docker-compose pull && docker-compose down && docker-compose up

depends_on:
  - app

trigger:
  event:
    - promote
    - rollback
